# Generated by Django 5.2.4 on 2025-08-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_typingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingresult',
            name='typos',
            field=models.IntegerField(default=0),
        ),
    ]
